import React from 'react';

interface Benefit {
    title: string;
    description: string;
}

const BenefitsSection: React.FC = () => {
    const benefits: Benefit[] = [
        {
            title: 'Achieve your Financial Goals',
            description:
                "Achieving one's financial goals, whether short-term (a vacation next year or buying a car in two years) or long-term (child's education abroad after 8 years or planning for retirement), requires an understanding of goals and how those goals can be achieved with the right plan. Our approach keeps your financial goals in focus to ensure you are able to achieve them.",
        },
        {
            title: 'Select the Right Funds',
            description:
                'Selecting the right funds is more than just looking at past performance and picking up the top ones! We follow a rigorous process which is a combination of objective and subjective parameters, such as returns being generated by a fund manager compared to risk being taken and volatility of the returns of a fund.',
        },
        {
            title: 'Experience Technology at its Best',
            description:
                'One of the reasons for the failure of investors to keep up with the investment plan is inordinate time being spent in managing investments. The Nivesh app helps you in tracking your investments on the go in a language that is easy to understand, which has been made possible due to many years of experience of the Nivesh team in building financial technology platforms.',
        },
        {
            title: 'Assisted by Qualified AMFI Registered Mutual Fund Distributors',
            description:
                'A mutual fund distributor plays an extremely important role in the entire process by guiding and handholding you throughout your investment journey. We have qualified mutual fund distributors as partners spread all across the country making it a unique proposition that is just right for you!',
        },
    ];

    return (
        <section className="py-20 md:py-32 bg-neutral-50">
            <div className="container-custom">
                {/* Section Header */}
                <div className="text-center mb-16">
                    <h2 className="text-3xl md:text-4xl font-semibold text-neutral-900 mb-4">
                        Benefits of Nivesh
                    </h2>
                </div>

                {/* Benefits List */}
                <div className="max-w-4xl mx-auto space-y-12">
                    {benefits.map((benefit, index) => (
                        <div
                            key={index}
                            className="group bg-white rounded-2xl p-8 shadow-sm border-2 border-transparent hover:border-primary hover:shadow-xl transition-all duration-300 hover:scale-[1.02] cursor-pointer"
                        >
                            {/* Title */}
                            <h3 className="text-xl md:text-2xl font-semibold text-neutral-900 mb-4 group-hover:text-primary transition-colors duration-300">
                                {benefit.title}
                            </h3>

                            {/* Description */}
                            <p className="text-neutral-600 leading-relaxed group-hover:text-neutral-900 transition-colors duration-300">
                                {benefit.description}
                            </p>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default BenefitsSection;
